# Generated by Django 6.0.4 on 2026-05-02 13:18

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded to Cloudinary in production', upload_to='products/images/')),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility text for screen readers', max_length=125)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in gallery — 0 shows first')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image shown on product cards in marketplace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use product base price', max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Units available for this variant combination')),
                ('sku_code', models.CharField(blank=True, help_text='Auto-generated unique SKU code', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product SKU',
                'verbose_name_plural': 'Product SKUs',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField()),
                ('photo', models.ImageField(blank=True, help_text='Optional photo uploaded to Cloudinary', null=True, upload_to='reviews/photos/')),
                ('seller_reply', models.TextField(blank=True, help_text='Seller can reply once — cannot edit after submitting')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='eg XL, Red, 128GB, Cotton', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Variant Option',
                'verbose_name_plural': 'Variant Options',
                'ordering': ['variant_type', 'value'],
            },
        ),
        migrations.CreateModel(
            name='VariantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg Size, Color, Storage, RAM, Material', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Variant Type',
                'verbose_name_plural': 'Variant Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_save', models.DecimalField(decimal_places=2, help_text='Price when added to wishlist — compared daily for price drop alerts', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, default='mdi:tag', help_text='Iconify icon name eg: heroicons:shopping-bag or mdi:phone', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on marketplace — lower number shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty for top-level categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('brand_new', 'Brand New (Sealed)'), ('new', 'New'), ('nigerian_used', 'Nigerian Used'), ('refurbished', 'Refurbished'), ('for_parts', 'For Parts Only')], default='new', max_length=15)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in NGN — individual SKUs can have different prices', max_digits=12)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='Discount percentage 0-50. 0 means no discount')),
                ('discount_until', models.DateTimeField(blank=True, help_text='Discount auto-expires at this datetime', null=True)),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('flash_sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special flash sale price — overrides discount_percent', max_digits=12, null=True)),
                ('flash_sale_start', models.DateTimeField(blank=True, null=True)),
                ('flash_sale_end', models.DateTimeField(blank=True, null=True)),
                ('flash_sale_quantity', models.PositiveIntegerField(blank=True, help_text='Limited quantity at flash sale price', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False = invisible to buyers. Auto-set False when all SKUs hit 0 stock')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured products appear at top of category — paid promotion')),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('restock_deadline', models.DateTimeField(blank=True, help_text='Auto-delete deadline. Set when all SKUs hit 0. 14 days from then.', null=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='PROTECT means category cannot be deleted if products exist in it', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
