# Generated by Django 6.0.4 on 2026-05-02 13:18

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(help_text='The store this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.sellerprofile'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sku',
            field=models.ForeignKey(blank=True, help_text='Link to specific SKU for variant-specific images', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='products.productsku'),
        ),
        migrations.AddField(
            model_name='review',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(help_text='Verified purchase proof — one review per order item', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product'),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='created_by_seller',
            field=models.ForeignKey(blank=True, help_text='Seller who first added this option — null if admin pre-loaded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_variant_options', to='stores.sellerprofile'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='variant_options',
            field=models.ManyToManyField(blank=True, help_text='The combination of variant options for this SKU', related_name='skus', to='products.variantoption'),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='variant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.varianttype'),
        ),
        migrations.AddField(
            model_name='category',
            name='required_variants',
            field=models.ManyToManyField(blank=True, help_text='Variant types sellers must fill when listing in this category', related_name='required_for_categories', to='products.varianttype'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='products.product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller'], name='products_pr_seller__1bcc9b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='products_pr_is_feat_a5d7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['condition'], name='products_pr_conditi_a55578_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='products_pr_search__98d711_gin'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'rating'], name='products_re_product_439051_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['buyer'], name='products_re_buyer_i_664061_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['sku_code'], name='products_pr_sku_cod_6962ce_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['stock'], name='products_pr_stock_08e2d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variantoption',
            unique_together={('variant_type', 'value')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
