# Generated by Django 6.0.4 on 2026-05-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='mdi:tag', help_text='Iconify icon name eg: heroicons:shopping-bag or mdi:phone', max_length=100),
        ),
    ]
