# Generated by Django 6.0.4 on 2026-06-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Uploaded to Cloudinary in production', max_length=500, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo uploaded to Cloudinary', max_length=500, null=True, upload_to='reviews/photos/'),
        ),
    ]
