# Generated by Django 6.0.4 on 2026-05-02 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, help_text='Used for guest checkout order confirmation emails', max_length=254)),
                ('guest_name', models.CharField(blank=True, max_length=255)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('order_ref', models.CharField(blank=True, help_text='Auto-generated unique order reference', max_length=20, unique=True)),
                ('payment_method', models.CharField(choices=[('pay_now', 'Pay Now (Online)'), ('pod', 'Pay on Delivery')], default='pay_now', max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('confirmed', 'Payment Confirmed'), ('pending_cash', 'Pending Cash (POD)'), ('failed', 'Payment Failed'), ('refunded', 'Refunded'), ('partial_refund', 'Partially Refunded')], default='pending', max_length=15)),
                ('fw_transaction_ref', models.CharField(blank=True, db_index=True, help_text='Flutterwave transaction reference for this order', max_length=100)),
                ('delivery_type', models.CharField(choices=[('door', 'Door Delivery'), ('pickup', 'Pickup Station')], default='door', max_length=10)),
                ('delivery_address', models.TextField(blank=True, help_text='Full delivery address for door delivery')),
                ('delivery_state', models.CharField(help_text='Nigerian state for delivery zone validation', max_length=50)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Products total before delivery and discount', max_digits=12)),
                ('total_delivery_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all seller delivery fees', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount deducted by coupon', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final amount charged = subtotal + delivery - discount', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of purchase — never changes', max_digits=12)),
                ('product_name', models.CharField(help_text='Product name snapshot at purchase time', max_length=255)),
                ('product_sku_code', models.CharField(help_text='SKU code snapshot at purchase time', max_length=50)),
                ('variant_description', models.CharField(blank=True, help_text='eg Black + 128GB — snapshot at purchase time', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='SellerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_confirmed', 'Payment Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delivered_paid', 'Delivered & Paid (POD)'), ('completed', 'Completed'), ('cancelled_buyer', 'Cancelled by Buyer'), ('cancelled_seller', 'Cancelled by Seller'), ('refund_initiated', 'Refund Initiated'), ('refunded', 'Refunded'), ('disputed', 'Under Dispute')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Total for this seller items only', max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee for this seller items', max_digits=8)),
                ('commission_rate', models.PositiveIntegerField(default=0, help_text='Commission % taken at time of order based on threshold')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual NGN amount taken as commission', max_digits=10)),
                ('seller_payout', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount seller actually receives after commission', max_digits=12)),
                ('tracking_number', models.CharField(blank=True, help_text='Optional courier tracking number', max_length=100)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_passed', models.BooleanField(blank=True, help_text='True=buyer accepted, False=buyer rejected at door', null=True)),
                ('inspection_notes', models.TextField(blank=True, help_text='Notes from delivery inspection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seller Order',
                'verbose_name_plural': 'Seller Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Django session key for guest carts', max_length=40, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_snapshot', models.DecimalField(decimal_places=2, help_text='Price at time of adding to cart — locked until checkout', max_digits=12)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
    ]
