# Generated by Django 6.0.4 on 2026-05-02 09:01

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Used as the login identifier instead of username', max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], default='buyer', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to deactivate account without deleting')),
                ('is_staff', models.BooleanField(default=False, help_text='Allows access to Django admin panel')),
                ('is_email_verified', models.BooleanField(default=False, help_text='User must verify email before buying or selling')),
                ('device_fingerprint', models.CharField(blank=True, help_text='FingerprintJS hash — used for relation banning', max_length=255)),
                ('ban_status', models.CharField(choices=[('none', 'Not Banned'), ('shadow', 'Shadow Banned'), ('hard', 'Hard Banned'), ('permanent', 'Permanently Banned')], default='none', max_length=10)),
                ('fraud_score', models.PositiveIntegerField(default=0, help_text='Increases on failed payment attempts. >=5 shadow ban, >=8 hard ban')),
                ('ban_reason', models.TextField(blank=True, help_text='Internal note explaining why this account was banned')),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('pod_count_this_month', models.PositiveIntegerField(default=0, help_text='Resets every month via Celery task')),
                ('pod_strikes', models.PositiveIntegerField(default=0, help_text='Cumulative POD strikes. 3 = permanent POD revocation')),
                ('pod_suspended_until', models.DateField(blank=True, help_text='POD suspended until this date after 2 monthly strikes', null=True)),
                ('currency_preference', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='NGN', max_length=3)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(db_index=True, max_length=255)),
                ('ban_type', models.CharField(choices=[('shadow', 'Shadow Banned'), ('hard', 'Hard Banned'), ('permanent', 'Permanently Banned')], max_length=10)),
                ('is_honeypot', models.BooleanField(default=False, help_text='If True, any device logging into this account gets banned')),
                ('ban_reason', models.TextField()),
                ('appeal_status', models.CharField(choices=[('none', 'No Appeal'), ('pending', 'Appeal Pending'), ('approved', 'Appeal Approved'), ('denied', 'Appeal Denied')], default='none', max_length=10)),
                ('appeal_note', models.TextField(blank=True, help_text='Admin notes on the appeal decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ban_records', to=settings.AUTH_USER_MODEL)),
                ('parent_ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_bans', to='accounts.banrecord')),
            ],
            options={
                'verbose_name': 'Ban Record',
                'verbose_name_plural': 'Ban Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['ban_status'], name='accounts_us_ban_sta_10e466_idx'),
        ),
        migrations.AddIndex(
            model_name='banrecord',
            index=models.Index(fields=['device_fingerprint'], name='accounts_ba_device__cf6e67_idx'),
        ),
        migrations.AddIndex(
            model_name='banrecord',
            index=models.Index(fields=['ban_type'], name='accounts_ba_ban_typ_e5f90b_idx'),
        ),
    ]
