# Generated by Django 6.0.4 on 2026-05-02 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Actual NGN amount discounted on this order', max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_ngn', models.DecimalField(decimal_places=2, help_text='How many NGN = 1 USD eg 1650.00', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only one rate should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Nexo', max_length=50)),
                ('platform_tagline', models.CharField(default='Nigerian Marketplace // Converge & Sell', max_length=100)),
                ('support_email', models.EmailField(default='support@nexo.ng', max_length=254)),
                ('support_whatsapp', models.CharField(blank=True, max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If True — site shows maintenance page to all non-admin users')),
                ('maintenance_message', models.TextField(blank=True, default='Nexo is undergoing scheduled maintenance. Back shortly!')),
                ('reserve_fund_percent', models.DecimalField(decimal_places=2, default=1.0, help_text='% of every Pay Now transaction that goes to reserve fund eg 1.00 = 1%', max_digits=4)),
                ('max_homepage_featured_stores', models.PositiveIntegerField(default=8, help_text='Maximum store cards shown in homepage featured section')),
                ('sub_price_1m', models.DecimalField(decimal_places=2, default=5000.0, help_text='1 month subscription price in NGN', max_digits=10)),
                ('sub_price_6m', models.DecimalField(decimal_places=2, default=25000.0, help_text='6 month subscription price in NGN', max_digits=10)),
                ('sub_price_12m', models.DecimalField(decimal_places=2, default=45000.0, help_text='12 month subscription price in NGN', max_digits=10)),
                ('sub_price_24m', models.DecimalField(decimal_places=2, default=80000.0, help_text='24 month subscription price in NGN', max_digits=10)),
                ('pod_limit_new', models.PositiveIntegerField(default=2, help_text='POD orders per month for new accounts (0-3 months)')),
                ('pod_limit_established', models.PositiveIntegerField(default=5, help_text='POD orders per month for established accounts (3m+)')),
                ('pod_limit_vip', models.PositiveIntegerField(default=8, help_text='POD orders per month for VIP buyers')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Auto-generated unique code eg NK7X2-P9QM4', max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off')], default='percentage', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (5-50) or fixed NGN amount', max_digits=5)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount in NGN to use this coupon', max_digits=10, null=True)),
                ('max_uses', models.PositiveIntegerField(default=100, help_text='Maximum total uses before coupon deactivates')),
                ('uses_count', models.PositiveIntegerField(default=0, help_text='Current total uses — auto-incremented on each use')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='How many times one user can use this coupon')),
                ('budget_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Platform coupons only — auto-deactivates when total discount hits this', max_digits=12, null=True)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount amount given so far', max_digits=12)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
