# Generated by Django 6.0.4 on 2026-05-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='sub_price_12m',
            field=models.DecimalField(decimal_places=2, default=5500000.0, help_text='12 month subscription price in NGN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sub_price_1m',
            field=models.DecimalField(decimal_places=2, default=600000.0, help_text='1 month subscription price in NGN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sub_price_24m',
            field=models.DecimalField(decimal_places=2, default=9000000.0, help_text='24 month subscription price in NGN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sub_price_6m',
            field=models.DecimalField(decimal_places=2, default=3000000.0, help_text='6 month subscription price in NGN', max_digits=10),
        ),
    ]
