# Generated by Django 6.0.4 on 2026-05-02 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current reserve fund balance in NGN', max_digits=14)),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=50000.0, help_text='Alert admin when balance drops below this amount', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reserve Fund',
                'verbose_name_plural': 'Reserve Fund',
            },
        ),
        migrations.CreateModel(
            name='ReserveFundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('contribution', 'Contribution (% of sale)'), ('disbursement', 'Disbursement (buyer compensation)'), ('manual_add', 'Manual Addition (admin)'), ('manual_deduct', 'Manual Deduction (admin)')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in NGN — positive for additions, negative for deductions', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Reserve fund balance after this transaction', max_digits=14)),
                ('reference', models.CharField(blank=True, help_text='Order ref or dispute ID that triggered this transaction', max_length=100)),
                ('note', models.TextField(blank=True, help_text='Admin note explaining this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who made this transaction — null for automatic contributions', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reserve_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.reservefund')),
            ],
            options={
                'verbose_name': 'Reserve Fund Log',
                'verbose_name_plural': 'Reserve Fund Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fw_reference', models.CharField(db_index=True, help_text='Flutterwave transaction reference — unique per transaction', max_length=100, unique=True)),
                ('fw_transaction_id', models.CharField(blank=True, help_text='Flutterwave internal transaction ID', max_length=100)),
                ('payment_type', models.CharField(choices=[('purchase', 'Product Purchase'), ('subscription', 'Seller Subscription'), ('featured', 'Featured Listing'), ('refund', 'Refund'), ('payout', 'Seller Payout')], default='purchase', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('disputed', 'Disputed')], default='pending', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in NGN', max_digits=12)),
                ('currency', models.CharField(default='NGN', help_text='Currency code — NGN or USD', max_length=3)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of buyer at payment time', null=True)),
                ('device_fingerprint', models.CharField(blank=True, help_text='FingerprintJS hash at payment time', max_length=255)),
                ('raw_webhook', models.JSONField(blank=True, help_text='Complete raw webhook payload from Flutterwave', null=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, help_text='When webhook arrived at our server', null=True)),
                ('order_created', models.BooleanField(default=False, help_text='True once order successfully created after payment')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure from Flutterwave', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fw_reference'], name='payments_pa_fw_refe_434228_idx'), models.Index(fields=['status'], name='payments_pa_status_e851bf_idx'), models.Index(fields=['payment_type'], name='payments_pa_payment_4933a0_idx'), models.Index(fields=['buyer'], name='payments_pa_buyer_i_7d31a0_idx'), models.Index(fields=['order_created', 'status'], name='payments_pa_order_c_81d4e9_idx')],
            },
        ),
    ]
