# Generated by Django 6.0.4 on 2026-05-02 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller')], help_text='Whether message is from admin or seller', max_length=10)),
                ('message', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='disputes/messages/')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispute Message',
                'verbose_name_plural': 'Dispute Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerStrike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('warning', 'Warning (Strike 1)'), ('forced', 'Forced Refund (Strike 2)'), ('suspended', 'Store Suspended (Strike 3)'), ('banned', 'Permanently Banned (Strike 4)')], max_length=10)),
                ('reason', models.TextField(help_text='Detailed reason for this strike')),
                ('action_taken', models.TextField(blank=True, help_text='eg Store suspended, ₦50,000 deducted from payout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seller Strike',
                'verbose_name_plural': 'Seller Strikes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('broken', 'Item Arrived Broken/Damaged'), ('wrong_item', 'Wrong Item Received'), ('not_described', 'Not as Described'), ('not_delivered', 'Item Not Delivered'), ('missing_parts', 'Missing Parts/Accessories')], max_length=20)),
                ('description', models.TextField(help_text='Buyer describes what went wrong in detail')),
                ('status', models.CharField(choices=[('open', 'Open — Awaiting Seller Response'), ('seller_responded', 'Seller Responded'), ('escalated', 'Escalated to Admin'), ('resolved_refund', 'Resolved — Refund Issued'), ('resolved_kept', 'Resolved — Buyer Keeps Item'), ('resolved_replace', 'Resolved — Replacement Sent'), ('closed', 'Closed')], default='open', max_length=20)),
                ('evidence_photo_1', models.ImageField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('evidence_photo_2', models.ImageField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('evidence_photo_3', models.ImageField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('evidence_video_url', models.URLField(blank=True, help_text='Optional video evidence link')),
                ('seller_response', models.TextField(blank=True, help_text='Seller response to the dispute')),
                ('seller_responded_at', models.DateTimeField(blank=True, null=True)),
                ('admin_decision', models.TextField(blank=True, help_text='Admin final binding decision')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Compensation amount issued to buyer in NGN', max_digits=12, null=True)),
                ('compensation_source', models.CharField(blank=True, choices=[('seller', 'From Seller Payout'), ('reserve_fund', 'From Platform Reserve Fund'), ('both', 'Split Between Seller and Fund')], help_text='Where compensation money came from', max_length=20)),
                ('refund_fw_reference', models.CharField(blank=True, help_text='Flutterwave refund transaction reference', max_length=100)),
                ('seller_response_deadline', models.DateTimeField(blank=True, help_text='48hr deadline for seller to respond before auto-escalation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved this dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
