# Generated by Django 6.0.4 on 2026-05-02 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disputes', '0001_initial'),
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_received', to='stores.sellerprofile'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='seller_order',
            field=models.OneToOneField(help_text='One dispute per seller order maximum', on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='orders.sellerorder'),
        ),
        migrations.AddField(
            model_name='disputemessage',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='disputemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerstrike',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='sellerstrike',
            name='issued_by',
            field=models.ForeignKey(help_text='Admin who issued this strike', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strikes_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerstrike',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='stores.sellerprofile'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status'], name='disputes_di_status_124397_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['seller'], name='disputes_di_seller__47e0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['buyer'], name='disputes_di_buyer_i_723775_idx'),
        ),
    ]
