# Generated by Django 6.0.4 on 2026-05-02 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(help_text='Public name of the store eg Nike Store Lagos', max_length=100, unique=True)),
                ('store_slug', models.SlugField(blank=True, help_text='URL-friendly version of store name eg nike-store-lagos', max_length=120, unique=True)),
                ('store_description', models.TextField(blank=True, help_text='Short bio shown on storefront eg Lagos-based Nike dealer')),
                ('logo', models.ImageField(blank=True, help_text='Store logo — shown on storefront and product cards', null=True, upload_to='stores/logos/')),
                ('banner_image', models.ImageField(blank=True, help_text='Campaign banner image shown at top of store page', null=True, upload_to='stores/banners/')),
                ('banner_headline', models.CharField(blank=True, help_text='Bold headline text on banner eg Premium Nike Footwear', max_length=60)),
                ('banner_subtext', models.CharField(blank=True, help_text='Secondary text eg Free delivery within Lagos', max_length=120)),
                ('banner_bg_color', models.CharField(default='#111118', help_text='Background color of banner in hex eg #FF4D00', max_length=7)),
                ('banner_accent_color', models.CharField(default='#FF4D00', help_text='Accent color for text highlights and buttons on banner', max_length=7)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Nigerian number with country code eg 2348012345678', max_length=20)),
                ('account_type', models.CharField(choices=[('individual', 'Individual (BVN only)'), ('business', 'Business (CAC registered)')], default='individual', max_length=10)),
                ('bvn_verified', models.BooleanField(default=False, help_text='BVN verified via Flutterwave onboarding')),
                ('cac_number', models.CharField(blank=True, help_text='CAC registration number for business accounts', max_length=20)),
                ('cac_verified', models.BooleanField(default=False, help_text='CAC number verified by admin')),
                ('bank_account_number', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(blank=True, help_text='Name on the bank account — must match BVN/CAC', max_length=255)),
                ('fw_subaccount_id', models.CharField(blank=True, help_text='Flutterwave subaccount ID — auto-created on approval', max_length=100)),
                ('fw_subaccount_code', models.CharField(blank=True, help_text='Flutterwave subaccount code used in payment splits', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Subscription Expired'), ('banned', 'Permanently Banned')], default='pending', max_length=10)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before store goes live')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason shown to seller if application rejected')),
                ('is_on_vacation', models.BooleanField(default=False, help_text='Store visible but cart disabled during vacation')),
                ('vacation_return_date', models.DateField(blank=True, help_text='Shown to buyers as expected return date', null=True)),
                ('allow_pod', models.BooleanField(default=True, help_text='Seller can disable POD for their store entirely')),
                ('strike_count', models.PositiveIntegerField(default=0, help_text='Dispute strikes. 3 = suspension, 4 = permanent ban')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-calculated average of all product ratings', max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0, help_text='Total number of reviews across all products')),
                ('current_commission_rate', models.PositiveIntegerField(default=0, help_text='Current commission % based on monthly revenue threshold')),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Running total for current month — reset by Celery monthly', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this store', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stores', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='The user account this store belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Profile',
                'verbose_name_plural': 'Seller Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('homepage', 'Homepage Featured Store'), ('store', 'Featured Store'), ('product', 'Featured Product')], max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fw_transaction_ref', models.CharField(max_length=100, unique=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_listings', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_listings', to='stores.sellerprofile')),
            ],
            options={
                'verbose_name': 'Featured Listing',
                'verbose_name_plural': 'Featured Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='Nigerian state this zone covers eg Lagos', max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Delivery fee in NGN for this state', max_digits=8)),
                ('estimated_days', models.PositiveIntegerField(default=1, help_text='Estimated delivery days eg 1 for same day, 2 for next day')),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='stores.sellerprofile')),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['state'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('1m', 'Starter (1 Month)'), ('6m', 'Standard (6 Months)'), ('12m', 'Pro (1 Year)'), ('24m', 'Elite (2 Years)')], max_length=3)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in NGN', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fw_transaction_ref', models.CharField(help_text='Flutterwave transaction reference for this payment', max_length=100, unique=True)),
                ('warning_30_sent', models.BooleanField(default=False)),
                ('warning_7_sent', models.BooleanField(default=False)),
                ('warning_1_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='stores.sellerprofile')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['store_slug'], name='stores_sell_store_s_fc16db_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['status'], name='stores_sell_status_0fd5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['is_approved'], name='stores_sell_is_appr_2e245c_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredlisting',
            index=models.Index(fields=['is_active', 'ends_at'], name='stores_feat_is_acti_e94638_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryzone',
            unique_together={('seller', 'state')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='stores_subs_status_bbb81b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='stores_subs_end_dat_f9b6c5_idx'),
        ),
    ]
