# Generated by Django 6.0.4 on 2026-06-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name eg Fashion Hero, Electronics Banner', max_length=100)),
                ('image', models.ImageField(help_text='High quality banner/header image', upload_to='storefront/templates/')),
                ('category_hint', models.CharField(blank=True, help_text='Optional category suggestion eg Fashion, Electronics, General', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Storefront Image',
                'verbose_name_plural': 'Storefront Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='store_name_last_changed',
            field=models.DateTimeField(blank=True, help_text='Last time store name was changed — enforces 3-month rule', null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Header image selected from admin gallery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_using', to='stores.storefrontimage'),
        ),
    ]
