# Generated by Django 6.0.4 on 2026-06-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storefrontimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='bestsellers_label',
            field=models.CharField(blank=True, default='Bestsellers', max_length=40),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='hero_cta_text',
            field=models.CharField(blank=True, default='Shop Now', help_text='Button text on hero', max_length=30),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='hero_headline',
            field=models.CharField(blank=True, help_text='Big bold headline eg NEW SEASON NEW STYLE', max_length=80),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='hero_layout_style',
            field=models.CharField(choices=[('split', 'Split (image one side, text other)'), ('overlay', 'Overlay (text on full image)')], default='split', help_text='Split = image beside text like default template. Overlay = text floats on full-width image.', max_length=8),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='hero_subtext',
            field=models.CharField(blank=True, help_text='Short paragraph under headline', max_length=160),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='hero_text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='In split layout, controls which side text sits on. In overlay, controls text alignment within the image.', max_length=6),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='new_arrivals_label',
            field=models.CharField(blank=True, default='New Arrivals', max_length=40),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='promo_banner_bg',
            field=models.CharField(default='#1C0F0A', max_length=7),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='promo_banner_text',
            field=models.CharField(blank=True, help_text='eg UP TO 40% OFF ON SELECTED ITEMS', max_length=80),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='show_bestsellers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='show_new_arrivals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='show_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='show_promo_banner',
            field=models.BooleanField(default=True),
        ),
    ]
