# Generated by Django 6.0.4 on 2026-06-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_sellerprofile_bestsellers_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='trust_badge_style',
            field=models.CharField(choices=[('bar', 'Bar single dark strip with icons'), ('cards', 'Cards individual rounded icon cards')], default='bar', help_text='Visual style for the trust badges section', max_length=6),
        ),
    ]
