# Generated by Django 6.0.4 on 2026-06-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_sellerprofile_trust_badge_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='newsletter_headline',
            field=models.CharField(blank=True, default='Join our newsletter', help_text='Headline text on the newsletter signup strip', max_length=80),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='store_tagline',
            field=models.CharField(blank=True, default='NEW ARRIVALS', help_text='Small label above hero headline eg NEW SEASON or TRENDING NOW', max_length=40),
        ),
    ]
