# Generated by Django 6.0.4 on 2026-06-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_sellerprofile_newsletter_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='hero_text_color',
            field=models.CharField(default='#FAF7F5', help_text='Color of headline and subtext on the hero section', max_length=7),
        ),
    ]
