# Generated by Django 6.0.4 on 2026-06-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_sellerprofile_hero_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Campaign banner image shown at top of store page', max_length=500, null=True, upload_to='stores/banners/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Store logo — shown on storefront and product cards', max_length=500, null=True, upload_to='stores/logos/'),
        ),
        migrations.AlterField(
            model_name='storefrontimage',
            name='image',
            field=models.ImageField(help_text='High quality banner/header image', max_length=500, upload_to='storefront/templates/'),
        ),
    ]
