# Generated by Django 6.0.4 on 2026-05-02 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(help_text='Type of email — matches notification type', max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent Successfully'), ('failed', 'Failed to Send'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', 'email_type'], name='notificatio_recipie_0cb1ea_idx'), models.Index(fields=['status'], name='notificatio_status_18a272_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('dispute_update', 'Dispute Status Update'), ('refund_processed', 'Refund Processed'), ('price_drop', 'Price Drop on Wishlist'), ('review_reminder', 'Leave a Review'), ('pod_allowance_low', 'POD Allowance Running Low'), ('new_order', 'New Order Received'), ('dispute_opened', 'Dispute Opened Against You'), ('strike_issued', 'Strike Issued'), ('sub_expiring_30', 'Subscription Expiring in 30 Days'), ('sub_expiring_7', 'Subscription Expiring in 7 Days'), ('sub_expiring_1', 'Subscription Expiring Tomorrow'), ('sub_expired', 'Subscription Expired'), ('store_suspended', 'Store Suspended'), ('low_stock', 'Product Low Stock'), ('product_deleted', 'Product Auto-Deleted'), ('new_review', 'New Product Review'), ('payout_processed', 'Payout Processed'), ('featured_expiring', 'Featured Listing Expiring'), ('seller_pending', 'New Seller Pending Approval'), ('dispute_escalated', 'Dispute Escalated to Admin'), ('reserve_fund_low', 'Reserve Fund Below Threshold'), ('strike_threshold', 'Seller Reached Strike Threshold'), ('suspicious_payment', 'Suspicious Payment Flagged'), ('appeal_submitted', 'Ban Appeal Submitted'), ('webhook_failed', 'Payment Webhook Failed')], max_length=30)),
                ('title', models.CharField(help_text='Short title shown in notification bell dropdown', max_length=100)),
                ('message', models.TextField(help_text='Full notification message')),
                ('link', models.CharField(blank=True, help_text='URL to navigate to when notification clicked', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object eg order ID, dispute ID', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object eg order, dispute, product', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
